### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Okilele56** [hj91/node-red-contrib-peak-value-calculator#1]
Hello,
Thank you for this node.
Would it also be possible to add the timestamp when the peak appears? Or a list of timestamps if the peak is reached several times.

**Comment by hj91** [comment]
Hi...

Interesting idea. I will check it ..

but for now - you can log the values directly innto influxdb and get automatic timestamps added to every reading. 

Let me know if it works for you, else we might require modifying code ...

**Comment by hj91** [comment]
I will create a seperate node for required functionality - this node will not be changed of its core logic.
